spring:
  datasource:
    url: jdbc:h2:mem:test
  liquibase:
    change-log: classpath:db/changelog/master.xml
  security:
    user:
      name: admin
      password: 1234.

  jpa:
    show-sql: false

