spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/example
    driver-class-name: org.postgresql.Driver

    username: example
    password: example


  liquibase:
    contexts: prod
    change-log: classpath:db/changelog/master_prod.xml

  jpa:
    hibernate:
      ddl-auto: update