spring:
  datasource:
    driver-class-name: org.h2.Driver
    url:  jdbc:h2:mem:test
  liquibase:
    contexts: dev
    change-log: classpath:db/changelog/master2.xml

  jpa:
    hibernate:
      ddl-auto: validate